# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-01 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180104_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(default='Unknown', max_length=128),
            preserve_default=False,
        ),
    ]
