# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-03 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_profile_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userparticipatesonteam',
            unique_together=set([('team', 'user')]),
        ),
    ]
