# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-20 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20180214_0142'),
        ('accounts', '0004_auto_20180203_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='panel_active_teampc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.TeamParticipatesChallenge'),
        ),
    ]
