# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180226_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age\u200c'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='National code\u200c'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(max_length=128, verbose_name='Organization\u200c'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Mobile number\u200c'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone number\u200c'),
        ),
    ]
