# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180212_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='should_pay',
            field=models.BooleanField(default=False),
        ),
    ]
