# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180218_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
