# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180227_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='panel_active_teampc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.TeamParticipatesChallenge'),
        ),
    ]
