# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180306_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
