# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_data',
            field=models.NullBooleanField(),
        ),
    ]
