# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-19 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180219_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='has_paid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='should_pay',
        ),
    ]
