# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_confirm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Mobile number\u200c'),
        ),
    ]
