# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_fullname_eng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fullname_eng',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name in English'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name in English'),
        ),
    ]
