# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190306_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sharif_id_pass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sharif ID Password'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sharif_id_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sharif ID Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name_eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name in English'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name in English'),
        ),
    ]
