# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-26 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
    ]
