# Generated by Django 2.0 on 2018-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentflag',
            name='replay',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
