# Generated by Django 2.0 on 2018-01-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_commentflag_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentflag',
            name='replay',
            field=models.CharField(max_length=300, verbose_name='replay'),
        ),
    ]
