# Generated by Django 2.0 on 2018-01-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0005_auto_20180101_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentflag',
            name='replay',
            field=models.CharField(db_index=True, max_length=300, verbose_name='replay'),
        ),
    ]
