# Generated by Django 2.0 on 2018-01-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0006_auto_20180101_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentflag',
            name='replay',
        ),
    ]
