# Generated by Django 2.0 on 2018-01-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0007_remove_commentflag_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.TextField(default=1, max_length=3000, verbose_name='replay'),
            preserve_default=False,
        ),
    ]
