# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0008_comment_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replay',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(default=1, max_length=3000, verbose_name='reply'),
            preserve_default=False,
        ),
    ]
