# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
