# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-16 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
