# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20190121_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('team', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(null=True, upload_to='staff_pic')),
            ],
        ),
    ]
