# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-16 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(null=True, upload_to='staff_pic'),
        ),
    ]
