# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_auto_20190116_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='color',
            field=models.CharField(default='red', max_length=10),
        ),
    ]
