# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.URLField()),
                ('shortened', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
