# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('elim', 'Elimination'), ('double', 'Double Elimination'), ('league', 'League')], max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='infra_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='participant',
            name='depend_method',
            field=models.CharField(choices=[('winner', 'Winner'), ('loser', 'Loser'), ('itself', 'Itself')], max_length=128),
        ),
        migrations.AlterField(
            model_name='teamsubmission',
            name='infra_token',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
