# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180120_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubmission',
            name='infra_compile_token',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
