# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180121_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsubmission',
            name='language',
            field=models.CharField(choices=[('c++', 'C++'), ('java', 'Java'), ('python2', 'Python 2'), ('python3', 'Python 3')], default='java', max_length=128),
        ),
    ]
