# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Map'),
            preserve_default=False,
        ),
    ]
