# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 13:38
from __future__ import unicode_literals

from django.db import migrations


def delete_null_matches(apps, schema):
    single_match = apps.get_model('game', 'SingleMatch')
    for match in single_match.objects.all():
        match.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0008_singlematch_map'),
    ]

    operations = [
        migrations.RunPython(delete_null_matches)
    ]
