# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20180126_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
