# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-03 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180203_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_map_competitions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamparticipateschallenge',
            unique_together=set([('team', 'challenge')]),
        ),
        migrations.AlterUniqueTogether(
            name='useracceptsteaminchallenge',
            unique_together=set([('team', 'user')]),
        ),
    ]
