# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_map_competitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsubmission',
            name='language',
            field=models.CharField(choices=[('cpp', 'C++'), ('java', 'Java'), ('py3', 'Python 3')], default='java', max_length=128),
        ),
    ]
