# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-01 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20180130_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('failed', 'Failed'), ('done', 'Done'), ('waiting', 'Waiting')], default='waiting', max_length=128),
        ),
    ]
