# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-31 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20180130_1959'),
        ('game', '0012_singlematch_status'),
    ]

    operations = [
    ]
