# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_singlematch_status'),
        ('game', '0013_merge_20180131_1444'),
    ]

    operations = [
    ]
