# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-05 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20180203_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlematch',
            name='done',
        ),
    ]
