# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_singlematch_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
