# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_merge_20180202_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='game.Competition'),
        ),
    ]
