# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20180202_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('elim', 'Elimination'), ('double', 'Double Elimination'), ('league', 'League'), ('friendly', 'Friendly')], max_length=128),
        ),
    ]
