# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-13 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_singlematch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
