# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsubmission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='game.TeamParticipatesChallenge'),
        ),
    ]
