# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_competition_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamparticipateschallenge',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='accounts.Team'),
        ),
    ]
