# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20180306_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.TeamParticipatesChallenge'),
        ),
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.FileField(upload_to='maps/'),
        ),
    ]
