# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_confirm_data'),
        ('game', '0023_auto_20190207_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('single_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.SingleMatch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Team')),
            ],
        ),
    ]
