# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 09:59
from __future__ import unicode_literals

import compress_storage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_teamrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='file',
            field=compress_storage.models.ZipFileField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
