# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20190208_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlematch',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('failed', 'Failed'), ('done', 'Done'), ('waiting', 'Waiting'), ('waitacc', 'Wating to accept'), ('rejected', 'Rejected')], default='waiting', max_length=128),
        ),
    ]
