# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 12:07
from __future__ import unicode_literals

import apps.game.models.competition
import compress_storage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20190208_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='file',
            field=compress_storage.models.ZipFileField(blank=True, null=True, upload_to=apps.game.models.competition.map_directory_path),
        ),
    ]
