# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20190208_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
