# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20190209_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamparticipateschallenge',
            name='allow_random',
            field=models.NullBooleanField(),
        ),
    ]
