# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-02 07:20
from __future__ import unicode_literals

import apps.game.models.competition
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_teamparticipateschallenge_allow_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='part1_log',
            field=models.FileField(blank=True, null=True, upload_to=apps.game.models.competition.get_log_file_directory),
        ),
        migrations.AddField(
            model_name='singlematch',
            name='part2_log',
            field=models.FileField(blank=True, null=True, upload_to=apps.game.models.competition.get_log_file_directory),
        ),
    ]
