# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_auto_20190302_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlematch',
            name='part1_log',
            field=models.FileField(blank=True, null=True, upload_to='logs/'),
        ),
        migrations.AlterField(
            model_name='singlematch',
            name='part2_log',
            field=models.FileField(blank=True, null=True, upload_to='logs/'),
        ),
    ]
